import { validatePhoneNumber } from "../ReusableComponents/CommonFunctions";




export const storeForm = {
    formlayout: "vertical",
    fieldsArray: [
        {
            type : "file",
            label: "Store LOGO",
            name: "storeLogo",
            rules: [{ required: true, message: 'Please upload store Logo' }],
            placeholder: "Store LOGO",
            xs: 24,
            sm: 16,
            md: 12,
            lg: 12,
            labelCol: "",
            wrapperCol: "",
            value: "",
        },
        {
            type : "file",
            label: "Store Fevicon",
            name: "storeFevicon",
            rules: [{ required: true, message: 'Please upload store Fevicon' }],
            placeholder: "Store Fevicon",
            xs: 24,
            sm: 16,
            md: 12,
            lg: 12,
            labelCol: "",
            wrapperCol: "",
            value: "",
        },
        {   
            type: "text",
            label: "Address",
            name: "address",
            rules: [
                { required: true, message: 'Please enter address' },
                { min: 4, message: 'address must be at least 4 characters long' }
            ],
            placeholder: "Address",
            xs: 24,
            sm: 16,
            md: 12,
            lg: 12,
            labelCol: "",
            wrapperCol: "",
            value: "",
            },
            {   
                type: "text",
                label: "Pincode",
                name: "pincode",
                rules: [
                    { required: true, message: 'Please enter Pincode' },
                    { min: 6, message: 'address must be at least 6 characters long' }
                ],
                placeholder: "Pincode",
                xs: 24,
                sm: 16,
                md: 12,
                lg: 12,
                labelCol: "",
                wrapperCol: "",
                value: "",
                }, 
            {
                    type: "phonenumber",
                    label: "Contact Number*",
                    name: "contactNumber",
                    rules: [
                        { required: true, message: 'Please enter contact number' },
                        { validator: validatePhoneNumber }
                    ],
                    placeholder: "Contact Number",
                    xs: 24,
                    sm: 16,
                    md: 12,
                    lg: 12,
                    labelCol: "",
                    wrapperCol: "",
                    value: "",
                }, 
                {
                    type: "email",
                    label: "Email",
                    name: "email",
                    rules: [
                        { required: true, message: 'Please enter email' },
                        { type: 'email', message: 'Please enter a valid email' },
                    ],
                    placeholder: "Email",
                    xs: 24,
                    sm: 16,
                    md: 12,
                    lg: 12,
                    labelCol: "",
                    wrapperCol: "",
                    value: "",
                   },
                   {
                    type: "phonenumber",
                    label: "WhatsApp Number*",
                    name: "whatsappNumber",
                    rules: [
                        { required: true, message: 'Please enter WhatsApp number' },
                        { validator: validatePhoneNumber }
                    ],
                    placeholder: "WhatsApp Number",
                    xs: 24,
                    sm: 16,
                    md: 12,
                    lg: 12,
                    labelCol: "",
                    wrapperCol: "",
                    value: "",
                },
                {
                    type: "text",
                    label: "Warehouse Name",
                    name: "warehouseName",
                    rules: [{ required: true, message: 'Please enter Warehouse name' }],
                    placeholder: "Warehouse Name",
                    xs: 24,
                    sm: 16,
                    md: 12,
                    lg: 12,
                    labelCol: "",
                    wrapperCol: "",
                    value: "",
                },
                {   
                    type: "text",
                    label: "Warehouse Pincode",
                    name: "warehousepincode",
                    rules: [
                        { required: true, message: 'Please enter Warehouse Pincode' },
                        { min: 6, message: 'address must be at least 6 characters long' }
                    ],
                    placeholder: "Warehouse Pincode",
                    xs: 24,
                    sm: 16,
                    md: 12,
                    lg: 12,
                    labelCol: "",
                    wrapperCol: "",
                    value: "",
                    },
                    // {
                    //     type: "select",
                    //     label: "Day",
                    //     name: "selectedDay",
                    //     rules: [{ required: true, message: 'Please select a day' }],
                    //     placeholder: "Select a day",
                    //     xs: 4,
                    //     sm: 4,
                    //     md: 4,
                    //     lg: 4,
                    //     labelCol: "",
                    //     wrapperCol: "",
                    //     value:"", // Replace with your state value
                    // },
                    {
                        type: "text",
                        label: "Social Profiles",
                        name: "socialProfiles",
                        rules: [{ required: true, message: 'Please enter Social Profiles name' }],
                        placeholder: "Social Profiles",
                        xs: 24,
                        sm: 16,
                        md: 12,
                        lg: 12,
                        labelCol: "",
                        wrapperCol: "",
                        value: "",
                    },
                    {
                        type: "text",
                        label: "Policies",
                        name: "policies",
                        rules: [{ required: true, message: 'Please enter Policies' }],
                        placeholder: "Policies",
                        xs: 24 ,
                        sm: 16,
                        md: 12,
                        lg: 12,
                        labelCol: "",
                        wrapperCol: "",
                        value: "",
                    },
                     {
                        type: "select",
                        label: "Day",
                        name: "selectedDay",
                        rules: [{ required: true, message: 'Please select a day' }],
                        placeholder: "Select a day",
                        xs: 4,
                        sm: 4,
                        md: 4,
                        lg: 4,
                        labelCol: "",
                        wrapperCol: "",
                        value:"", // Replace with your state value
                    },  
                     {
                        type: "radio",
                        label: "Guest Check-Out",
                        name: "guestCheckOut",
                        rules: [{ required: true, message: 'Please choose Guest Check-Out!' }],
                        xs: 12, // Adjust the xs, sm, md, lg values as needed
                        sm: 12,
                        md: 12,
                        lg: 12,
                        labelCol: "",
                        wrapperCol: "",
                        value: "off", // Update with the selected value ("on" or "off")
                        options: [
                            { value: "on", label: "On" },
                            { value: "off", label: "Off" },
                        ],
                     },
                   ],
                    buttonSecction: {
                        justify: "end",
                        buttons: [
                            { name: "Add", type:"submit", color: "primary" },
                            { name: "Reset", fun: "reset", color: "default" },
                            { name: "Cancel", fun: "cancel", color: "secondary" },
                        ],
                },
                
                    
        
}